### ISSUE TITLE
Build fail on gatsby

### ISSUE THREAD

**Issue by BasitEllahi** [wizardrylabs/react-eventbrite-popup-checkout#25]
I am on localhost everything works, but when i do gatsby build i get an error  ReferenceError: self is not defined.

**Comment by cmdshepard** [comment]
@BasitEllahi thanks for opening this issue, I will try to replicate.
What version of Gatsby are you using?

**Comment by cmdshepard** [comment]
@BasitEllahi I managed to replicate this issue. [v2.0.6](https://github.com/wizardrylabs/react-eventbrite-popup-checkout/releases/tag/v2.0.6) should work with Gatsby build.

Marking this issue as closed.

Please open another ticket if the issue persists. Thanks again!
