### ISSUE TITLE
Error Next.js 13

### ISSUE THREAD

**Issue by tm-tm-tm** [wizardrylabs/react-eventbrite-popup-checkout#33]
Hey there, using this with Next.js 13.4.2 and receiving errors. 

[ReferenceError]: self is not defined

Worked with previous versions of Next, unable to get it working with this latest version. Let me know if you need any further context. Thanks!

**Comment by cmdshepard** [comment]
This issue has been fixed in [v2.0.11](https://github.com/wizardrylabs/react-eventbrite-popup-checkout/releases/tag/v2.0.11) - marking as closed
