### ISSUE TITLE
`componentWillMount` has been depreciated

### ISSUE THREAD

**Issue by allanlasser** [wizardrylabs/react-eventbrite-popup-checkout#4]
Thanks for writing this library, it was a big timesaver!

When running React 16.12, I get the following warning:

> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Since this library seems to be intended for client-side use only, I think that switching to use componentDidMount along with an initial state should be a sufficient solution. In my use, I've been conditionally rendering a link to the Eventbrite page as an initial state for the component.

**Comment by cmdshepard** [comment]
Hi @allanlasser - good to hear that you're taking advantage of this library.
I'd be willing to accept a PR to resolve this issue if you're up for it.

**Comment by cmdshepard** [comment]
`v2.0.0` resolves this issue
